
name: Push new image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    environment:
      name: ${{ github.ref_name }}

    runs-on: ubuntu-latest

    env:
      BRANCH: ${{ github.ref_name }}

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.before }}
        
    - name: Fetch latest changes
      run: git fetch origin ${{ github.ref_name }}

    - name: Reset local branch to match remote
      run: git reset --hard origin/${{ github.ref_name }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}

        
    - name: build and push image ${{ github.ref_name }}
      run: |
        docker build -t gustavovl/notigest-front:$BRANCH .
        docker push gustavovl/notigest-front:$BRANCH
